(define (problem thief_pursuit)
  (:domain dungeon)
  (:objects
    thief - adversary
    entrance - location
    exit_hall - location
    treasure_room - location
    guard_room - location
    armory - location
    library - location
    prison_cell - location
    secret_passage - location
    storage - location
    marketplace - location
    vault - location
    crypt - location
    observatory - location
    throne_room - location
    gallery - location
    great_hall - location
    dark_corridor - location
    kitchen - location
    smithy - location
    barracks - location
    alchemy_lab - location
    wine_cellar - location
    watchtower - location
    stable - location
    chapel - location
    torture_chamber - location
    dungeon_pit - location
    well_room - location
    servants_quarters - location
    bathhouse - location
    hallway_n - location
    hallway_s - location
    hallway_e - location
    hallway_w - location
    crossing - location
    courtyard - location
  )
  (:init
    (at thief storage)
    (connected entrance prison_cell)
    (connected entrance torture_chamber)
    (connected entrance barracks)
    (connected entrance chapel)
    (connected exit_hall observatory)
    (connected exit_hall armory)
    (connected exit_hall crossing)
    (connected exit_hall throne_room)
    (connected gallery barracks)
    (connected gallery prison_cell)
    (connected prison_cell entrance)
    (connected prison_cell gallery)
    (connected prison_cell great_hall)
    (connected great_hall chapel)
    (connected great_hall prison_cell)
    (connected great_hall library)
    (connected library vault)
    (connected library great_hall)
    (connected library hallway_s)
    (connected hallway_s crypt)
    (connected hallway_s library)
    (connected hallway_s watchtower)
    (connected watchtower servants_quarters)
    (connected watchtower hallway_s)
    (connected barracks gallery)
    (connected barracks courtyard)
    (connected barracks entrance)
    (connected chapel great_hall)
    (connected chapel stable)
    (connected chapel entrance)
    (connected chapel vault)
    (connected vault library)
    (connected vault secret_passage)
    (connected vault chapel)
    (connected vault crypt)
    (connected crypt hallway_s)
    (connected crypt dark_corridor)
    (connected crypt vault)
    (connected crypt servants_quarters)
    (connected servants_quarters watchtower)
    (connected servants_quarters guard_room)
    (connected servants_quarters crypt)
    (connected courtyard barracks)
    (connected courtyard kitchen)
    (connected courtyard torture_chamber)
    (connected torture_chamber entrance)
    (connected torture_chamber well_room)
    (connected torture_chamber courtyard)
    (connected torture_chamber stable)
    (connected stable chapel)
    (connected stable hallway_w)
    (connected stable torture_chamber)
    (connected stable secret_passage)
    (connected secret_passage vault)
    (connected secret_passage wine_cellar)
    (connected secret_passage stable)
    (connected secret_passage dark_corridor)
    (connected dark_corridor crypt)
    (connected dark_corridor observatory)
    (connected dark_corridor secret_passage)
    (connected dark_corridor guard_room)
    (connected guard_room servants_quarters)
    (connected guard_room alchemy_lab)
    (connected guard_room dark_corridor)
    (connected kitchen courtyard)
    (connected kitchen smithy)
    (connected kitchen well_room)
    (connected well_room torture_chamber)
    (connected well_room bathhouse)
    (connected well_room kitchen)
    (connected well_room hallway_w)
    (connected hallway_w stable)
    (connected hallway_w marketplace)
    (connected hallway_w well_room)
    (connected hallway_w wine_cellar)
    (connected wine_cellar secret_passage)
    (connected wine_cellar crossing)
    (connected wine_cellar hallway_w)
    (connected wine_cellar observatory)
    (connected observatory dark_corridor)
    (connected observatory exit_hall)
    (connected observatory wine_cellar)
    (connected observatory alchemy_lab)
    (connected alchemy_lab guard_room)
    (connected alchemy_lab throne_room)
    (connected alchemy_lab observatory)
    (connected smithy kitchen)
    (connected smithy storage)
    (connected smithy bathhouse)
    (connected bathhouse well_room)
    (connected bathhouse treasure_room)
    (connected bathhouse smithy)
    (connected bathhouse marketplace)
    (connected marketplace hallway_w)
    (connected marketplace dungeon_pit)
    (connected marketplace bathhouse)
    (connected marketplace crossing)
    (connected crossing wine_cellar)
    (connected crossing hallway_e)
    (connected crossing marketplace)
    (connected crossing exit_hall)
    (connected throne_room alchemy_lab)
    (connected throne_room hallway_n)
    (connected throne_room exit_hall)
    (connected storage smithy)
    (connected storage treasure_room)
    (connected treasure_room bathhouse)
    (connected treasure_room storage)
    (connected treasure_room dungeon_pit)
    (connected dungeon_pit marketplace)
    (connected dungeon_pit treasure_room)
    (connected dungeon_pit hallway_e)
    (connected hallway_e crossing)
    (connected hallway_e dungeon_pit)
    (connected hallway_e armory)
    (connected armory exit_hall)
    (connected armory hallway_e)
    (connected armory hallway_n)
    (connected hallway_n throne_room)
    (connected hallway_n armory)
  )
  (:goal (at thief treasure_room))
)
