(define (problem guard_pursuit)
  (:domain dungeon)
  (:objects
    guard - adversary
    entrance - location
    exit_hall - location
    treasure_room - location
    guard_room - location
    armory - location
    library - location
    prison_cell - location
    secret_passage - location
    storage - location
    marketplace - location
    vault - location
    crypt - location
    observatory - location
    throne_room - location
    gallery - location
    great_hall - location
    dark_corridor - location
    kitchen - location
    smithy - location
    barracks - location
    alchemy_lab - location
    wine_cellar - location
    watchtower - location
    stable - location
    chapel - location
    torture_chamber - location
    dungeon_pit - location
    well_room - location
    servants_quarters - location
    bathhouse - location
    hallway_n - location
    hallway_s - location
    hallway_e - location
    hallway_w - location
    crossing - location
    courtyard - location
  )
  (:init
    (at guard armory)
    (connected entrance hallway_n)
    (connected entrance vault)
    (connected entrance hallway_e)
    (connected entrance watchtower)
    (connected exit_hall throne_room)
    (connected exit_hall treasure_room)
    (connected exit_hall hallway_s)
    (connected exit_hall crossing)
    (connected gallery hallway_e)
    (connected gallery hallway_n)
    (connected hallway_n entrance)
    (connected hallway_n gallery)
    (connected hallway_n wine_cellar)
    (connected wine_cellar watchtower)
    (connected wine_cellar hallway_n)
    (connected wine_cellar crypt)
    (connected crypt kitchen)
    (connected crypt wine_cellar)
    (connected crypt chapel)
    (connected chapel guard_room)
    (connected chapel crypt)
    (connected chapel alchemy_lab)
    (connected alchemy_lab storage)
    (connected alchemy_lab chapel)
    (connected hallway_e gallery)
    (connected hallway_e great_hall)
    (connected hallway_e entrance)
    (connected watchtower wine_cellar)
    (connected watchtower servants_quarters)
    (connected watchtower entrance)
    (connected watchtower kitchen)
    (connected kitchen crypt)
    (connected kitchen courtyard)
    (connected kitchen watchtower)
    (connected kitchen guard_room)
    (connected guard_room chapel)
    (connected guard_room dark_corridor)
    (connected guard_room kitchen)
    (connected guard_room storage)
    (connected storage alchemy_lab)
    (connected storage torture_chamber)
    (connected storage guard_room)
    (connected great_hall hallway_e)
    (connected great_hall well_room)
    (connected great_hall vault)
    (connected vault entrance)
    (connected vault smithy)
    (connected vault great_hall)
    (connected vault servants_quarters)
    (connected servants_quarters watchtower)
    (connected servants_quarters dungeon_pit)
    (connected servants_quarters vault)
    (connected servants_quarters courtyard)
    (connected courtyard kitchen)
    (connected courtyard marketplace)
    (connected courtyard servants_quarters)
    (connected courtyard dark_corridor)
    (connected dark_corridor guard_room)
    (connected dark_corridor throne_room)
    (connected dark_corridor courtyard)
    (connected dark_corridor torture_chamber)
    (connected torture_chamber storage)
    (connected torture_chamber barracks)
    (connected torture_chamber dark_corridor)
    (connected well_room great_hall)
    (connected well_room stable)
    (connected well_room smithy)
    (connected smithy vault)
    (connected smithy prison_cell)
    (connected smithy well_room)
    (connected smithy dungeon_pit)
    (connected dungeon_pit servants_quarters)
    (connected dungeon_pit hallway_w)
    (connected dungeon_pit smithy)
    (connected dungeon_pit marketplace)
    (connected marketplace courtyard)
    (connected marketplace hallway_s)
    (connected marketplace dungeon_pit)
    (connected marketplace throne_room)
    (connected throne_room dark_corridor)
    (connected throne_room exit_hall)
    (connected throne_room marketplace)
    (connected throne_room barracks)
    (connected barracks torture_chamber)
    (connected barracks crossing)
    (connected barracks throne_room)
    (connected stable well_room)
    (connected stable library)
    (connected stable prison_cell)
    (connected prison_cell smithy)
    (connected prison_cell secret_passage)
    (connected prison_cell stable)
    (connected prison_cell hallway_w)
    (connected hallway_w dungeon_pit)
    (connected hallway_w bathhouse)
    (connected hallway_w prison_cell)
    (connected hallway_w hallway_s)
    (connected hallway_s marketplace)
    (connected hallway_s observatory)
    (connected hallway_s hallway_w)
    (connected hallway_s exit_hall)
    (connected crossing barracks)
    (connected crossing armory)
    (connected crossing exit_hall)
    (connected library stable)
    (connected library secret_passage)
    (connected secret_passage prison_cell)
    (connected secret_passage library)
    (connected secret_passage bathhouse)
    (connected bathhouse hallway_w)
    (connected bathhouse secret_passage)
    (connected bathhouse observatory)
    (connected observatory hallway_s)
    (connected observatory bathhouse)
    (connected observatory treasure_room)
    (connected treasure_room exit_hall)
    (connected treasure_room observatory)
    (connected treasure_room armory)
    (connected armory crossing)
    (connected armory treasure_room)
  )
  (:goal (at guard hallway_s))
)
